// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4-E8igWMywqCfbW1RXitBSjG4_yCgbJw',
    appId: '1:140209402382:android:b88b885bf767630560425f',
    messagingSenderId: '140209402382',
    projectId: 'safehaven-f93a4',
    storageBucket: 'safehaven-f93a4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-dzgkkxeUlY_wZWk6aE_f0-Y2S1gykwo',
    appId: '1:140209402382:ios:4508149681f75c4460425f',
    messagingSenderId: '140209402382',
    projectId: 'safehaven-f93a4',
    storageBucket: 'safehaven-f93a4.appspot.com',
    androidClientId: '140209402382-ftvrjthm6ob64u0arkcv0iidagrr0c52.apps.googleusercontent.com',
    iosClientId: '140209402382-nkcqak31bl51fcpe09ehqi68806sh9iv.apps.googleusercontent.com',
    iosBundleId: 'com.example.miniproject',
  );
}
